In [1]:
# PYTORCH Basic Tutorial
# It is from a site https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [2]:
from __future__ import print_function
import torch

In [3]:
x=torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 1.4013e-45, 7.0295e+28],
        [6.1949e-04, 7.5019e+28, 1.6078e+19],
        [3.0989e+32, 1.6097e+19, 2.9390e+29],
        [2.0705e-19, 1.8062e+28, 2.9203e+32],
        [1.8465e+25, 1.7055e+28, 7.4409e+28]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.0055, 0.7537, 0.3443],
        [0.1805, 0.3808, 0.2073],
        [0.0842, 0.4871, 0.7619],
        [0.7626, 0.1350, 0.5659],
        [0.2398, 0.0805, 0.0284]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
print(x.size())

torch.Size([2])


## Torch Tensor를 numpy 배열로 변환하기 
- Torch Tensor가 cpu상에 있다면 Torch Tensor와 numpy 배열은 메모리 공간을 공유하기 때문에 하나를 변경하면, 다른 하나도 변경이 됨 

In [9]:
torchEx = torch.ones(5)
print(torchEx)

tensor([1., 1., 1., 1., 1.])


In [11]:
numpyEx = torchEx.numpy()
print(numpyEx)

[1. 1. 1. 1. 1.]


In [12]:
torchEx.add_(2)

tensor([3., 3., 3., 3., 3.])

In [13]:
print(torchEx)
print(numpyEx)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


# Numpy 배열을 Torch Tensor로 변환하기

In [16]:
import numpy as np
a = np.zeros(5)
b = torch.from_numpy(a)
np.add(a,2,out=a)

array([2., 2., 2., 2., 2.])

In [17]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
